### ISSUE TITLE
Retinanet

### ISSUE THREAD

**Issue by Y-J-Q-L** [swift1988/InsDist#2]
I am very interested in your work and would like to use your method for comparison. May I ask if you can share the RetinaNet experiment configuration file?

**Comment by swift1988** [comment]
Sorry for the delayed reply, and thanks for your attention.

This project has been removed from our GPU service. However, the configure file for all detectors follows the original one in mmdetection.

**Comment by Jocelyn-Jiaxin** [comment]
Thank you very much for your reply. 
Do you remember whether the GPU resources used at that time were A100 or 3090? How many cards did you use to run the program in parallel?

I look forward to your reply, and wish you success in your research.

**Comment by swift1988** [comment]
To the best of my recollection, this project is runed by a single 2080. But it is quite likely that I misremember it. :)

Based on my experience, using 8 GPUs may obtain slightly better KD results.

**Comment by Jocelyn-Jiaxin** [comment]
Thank you very much for your reply. I wish you success in your research.
